### ISSUE TITLE
Variables not found

### ISSUE THREAD

**Issue by lrybbs** [scuwyh2000/RandBox#12]
thanks for your work, however, when I run your code, I found some problem:

Traceback (most recent call last):
  File "f:\documents_lry\detectron2\detectron2\engine\train_loop.py", line 155, in train
    self.run_step()
  File "f:\documents_lry\detectron2\detectron2\engine\defaults.py", line 496, in run_step
    self._trainer.run_step()
  File "f:\documents_lry\detectron2\detectron2\engine\train_loop.py", line 310, in run_step
    loss_dict = self.model(data)
  File "D:\Anaconda3\envs\detectron\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\Documents_lry\RandBox\randbox\detector.py", line 296, in forward
    targets, x_boxes = self.prepare_targets(gt_instances)
  File "F:\Documents_lry\RandBox\randbox\detector.py", line 350, in prepare_targets
    d_boxes = self.prepare_concat(gt_boxes)
  File "F:\Documents_lry\RandBox\randbox\detector.py", line 330, in prepare_concat
    x = (x_start * 2. - 1.) * self.scale
NameError: name 'x_start' is not defined

there are not  'x_start' in function "self.prepare_concat(gt_boxes)", I can only found 'x_start' in function "model_predictions", could you please fix this problem?

**Comment by lrybbs** [comment]
and in line 297 of "detector.py", the variables "t" is also missing

**Comment by scuwyh2000** [comment]
Hi, sorry for that. You can update the [detector.py](https://github.com/scuwyh2000/RandBox/blob/main/randbox/detector.py) and [head.py](https://github.com/scuwyh2000/RandBox/blob/main/randbox/head.py). If there are any other bugs, feel free to list here.
